### ISSUE TITLE
TypeError in train.py

### ISSUE THREAD

**Issue by cahsmann** [qsb300/PhysNetTF2#1]
When running I keep getting a type error "Input 'y' of 'Mul' Op has type resource that does not match type float32 of argument 'x'" starting at line 238 of train.py. Do you know what would be causing this error? 
Thank you

**Comment by qsb300** [comment]
I don't know.
I don't bring this to workable condition by myself. 
My error comes earlier,
File "train.py", line 19, in <module>
    tf.compat.v1.disable_eager_execution()
AttributeError: module 'tensorflow._api.v1.compat.v1.compat' has no attribute 'v1' 
Even after I correct this one. I still get some similar error and I gave up.
I'm not very familiar with tensorflow. But it looks you have fixed those problem already?

The original  PhysNet should work fine with tensorflow 1.1. I tested.
https://github.com/MMunibas/PhysNet
